### ISSUE TITLE
what does the 'alcsync timestamp' exactly mean? 

### ISSUE THREAD

**Issue by mkdthanga** [Lora-net/lr1110_evk_demo_app#12] opened 2021-03-29 11:04 UTC
Hi,
I receive the device data 'alcsync timestamp' from the Semtech Lora cloud (topic in chirpstack AS: '#/integration'). I thought it is the Almanac update date of the Edge Tracker device, but it seems to be different when I checked the recent almanac updated date row in the LoRa Edge config (BLE Android App) .
If it is the timestamp when the device receives satellite coverage, the 'position timestamp' which is included in the 'position solution' element should be the same, but it varies from this 'alcsync timestamp', why is that?!
please see the screenshot (highlighted texts) below:
 
![image](https://user-images.githubusercontent.com/36918728/112827850-304ce180-908f-11eb-9071-867739b3767c.png)

can anyone please help me with this confusion about 'alcsync timestamp' received from Semtech LoRa Cloud Portal?
Regards,
Thangaraj

**Comment by matthieuantoine** [comment] 2021-03-29 14:35
This is a duplicate of https://github.com/Lora-net/lora_edge_tracker_ref_design/issues/2

**Closed as completed by matthieuantoine** 2021-03-29 14:35 UTC
Labels: duplicate
